name: clean_mvvm_project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  retrofit: ^4.0.3
  dio: ^5.3.4
  analyzer: ^6.2.0 #^6.2.0
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.1
  get_it: ^7.6.4
  lottie: ^2.6.0
  image_picker: ^1.0.4
  carousel_slider: ^4.2.1
  easy_localization: ^3.0.3
  flutter_phoenix: ^1.1.1
  rxdart: ^0.27.7
  freezed: ^2.4.5
  json_annotation: ^4.8.1
  internet_connection_checker: ^1.0.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4 #^8.0.4
  json_serializable: ^6.7.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BOD_B
      fonts:
         - asset: assets/fonts/BOD_B.ttf

#        - asset: assets/fonts/BOD_Bold.ttf
#          weight: 700
#        - asset: assets/fonts/BOD_SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/BOD_Medium.ttf
#          weight: 500
#        - asset: assets/fonts/BOD_regular.ttf
#          weight: 400
#        - asset: assets/fonts/BOD_Light.ttf
#          weight: 300